# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-28 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0006_remove_redundant_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('page', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lp_electric_category', to='pages.Page')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='lp_electric.Category')),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'categories',
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('price', models.FloatField(blank=True, db_index=True, null=True)),
                ('in_stock', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_popular', models.BooleanField(db_index=True, default=False)),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='lp_electric.Category')),
                ('page', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lp_electric_product', to='pages.Page')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=500)),
                ('page', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='pages.Page')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryPage',
            fields=[
            ],
            options={
                'proxy': True,
                'abstract': False,
            },
            bases=('pages.modelpage',),
        ),
        migrations.CreateModel(
            name='ProductPage',
            fields=[
            ],
            options={
                'proxy': True,
                'abstract': False,
            },
            bases=('pages.modelpage',),
        ),
    ]
