# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-04 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    def __init__(self, *args, **kwargs):
        super(Migration, self).__init__(*args, **kwargs)
        self.app_label = 'pages'

    dependencies = [
        ('lp_electric', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='_menu_title_de',
            field=models.CharField(blank=True, help_text='This field will be shown in the breadcrumbs, menu items and etc.', max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='_menu_title_en',
            field=models.CharField(blank=True, help_text='This field will be shown in the breadcrumbs, menu items and etc.', max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='_menu_title_ru',
            field=models.CharField(blank=True, help_text='This field will be shown in the breadcrumbs, menu items and etc.', max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='_title_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='_title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='content_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='content_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='content_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='h1_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='h1_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='h1_ru',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
