# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-08 07:38
from __future__ import unicode_literals

from django.db import migrations
from django.conf import settings

from lp_electric.models import Category
from pages.models import ModelPage


def set_custom_categories(apps, schema_editor):
    appended = {}
    for key, fields in settings.CATEGORIES.items():
        parent = None
        if 'parent' in fields.keys():
            parent_index = fields['parent']
            parent = appended[parent_index]
        page = ModelPage.objects.create(
            slug=fields['slug'],
            position=fields['position'],
            h1=fields['name']
        )
        category = Category.objects.create(
            name=fields['name'],
            parent=parent,
            page=page
        )
        appended[key] = category


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lp_electric', '0002_custom_pages_data'),
    ]

    operations = [
        migrations.RunPython(set_custom_categories),
    ]
