# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-08 07:38
from __future__ import unicode_literals

from django.db import migrations
from django.conf import settings

from pages.models import CustomPage, FlatPage


JOB_CONTENT = '''
<p>Требуется ответственный молодой человек на позицию продавца консультанта в один
    из наших магазинов. В задачи входит обслуживание постителей торгового зала с целью увеличения продаж.</p>
<h4>Требования:</h4>
<ul>
    <li>Внимательный</li>
    <li>Аккуратный</li>
    <li>Ответственный</li>
    <li>Организованный</li>
</ul>
<strong><p>Зарплата: от 30 000 рублей</p></strong>
<br><br>
'''


# Inspired by Django doc:
# https://docs.djangoproject.com/en/1.9/ref/contrib/sites/#enabling-the-sites-framework
def set_custom_pages(apps, schema_editor):
    def patch_parent(fields_):
        parent = fields_.get('parent', None)
        if parent:
            fields_['parent'] = CustomPage.objects.get(slug=parent)
            if parent == 'jobs':
                fields_['content'] = JOB_CONTENT

    for fields in settings.FLAT_PAGES.values():
        patch_parent(fields)
        FlatPage.objects.create(**fields)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lp_electric', '0004_products_data'),
    ]

    operations = [
        migrations.RunPython(set_custom_pages),
    ]
