# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-22 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lp_electric', '0006_flat_pages_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='name_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='value_de',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='value_en',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
